export declare const DISPLAY_NONE = "none";
export declare const DISPLAY_INLINE = "inline";
export declare const DISPLAY_BLOCK = "block";
export declare const DISPLAY_INLINE_BLOCK = "inline-block";
export declare const DISPLAY_FLEX = "flex";
export declare const DISPLAY_TABLE = "table";
export declare const DISPLAY_TABLE_ROW = "table-row";
export declare const DISPLAY_TABLE_CELL = "table-cell";
export declare const SIZE_AUTO = "auto";
export declare const OVERFLOW_VISIBLE = "visible";
export declare const OVERFLOW_HIDDEN = "hidden";
export declare const OVERFLOW_CLIP = "clip";
export declare const OVERFLOW_SCROLL = "scroll";
export declare const OVERFLOW_AUTO = "auto";
//# sourceMappingURL=layout.d.ts.map